baseURL = "http://system2.io/"
title = "System 2"
languageCode = "en-us"

# Theme to use
theme = "simple-theme"

# Pagination
paginate = 3
paginatePath = "page"

# Copyright
copyright = "© 2019 — Clint Ryan"

# Highlighting
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "vs"

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Menu
[menu]
  # Header
  [[menu.main]]
    url = "/post/"
    name = "blog"
    weight = 1
  [[menu.main]]
    url = "/about/"
    name = "about"
    weight = 2

  # Footer
  [[menu.footer]]
    url = "https://github.com/eastwood"
    name = "GitHub"
    weight = 1
  [[menu.footer]]
    url = "/post/index.xml"
    name = "RSS"
    weight = 2
  [[menu.footer]]
    url = "https://twitter.com/_eastwd"
    name = "Twitter"
    weight = 3


# Links format
[permalinks]
  post = "/:year/:month/:title/"

[params]
  # Date format (default: Jan 2, 2006)
  datefmt  = "Jan 2, 2006"
